# Classes
predictor:
  class: mowgli.predictor.example_predictor.example_predictor.ExamplePredictor

# Key settings
dataset: 'se2018t11'
kg: 'conceptnet'
outdir: './output'

# Other settings
evaluate_training: false
store_predictions: true
datarows: 10
