# Classes
predictor:
  class: mowgli.predictor.example_predictor.ExamplePredictor
  arguments: {
  }

# Key settings
dataset: 'physicaliqa-train-dev'
kg: 'conceptnet'
outdir: './output'

# Other settings
evaluate_training: false
store_predictions: true
datarows: 10

gpus: '2'
max_epochs: 1
accumulate_grad_batches: 1